### ISSUE TITLE
Implement claim period

### ISSUE THREAD

**Issue by EGreg** [Intercoin/AuctionContract#5]
1. In params, add claimPeriod (= 0 by default) right after endTime param. This is the number of seconds after endTime that the winners can call claimX() but the owner can't withdraw the money yet.

2. Please throw CantWithdrawDuringClaimPeriod() during withdraw() if claim period didn't end yet.

3. Also, if someone calls claimX() use a low-level call(), and `refund()` the user the operation was not done successfully. According to this document it is sufficient to check for an error being thrown, but you can also look for some positive `true` result if it's standard. Do this for NFTs, but also Communities and Subscriptions! (If needed, alter SubscriptionContract to clearly return true on successful start of subscription by external operator etc.)
 
```
Failed transactions will throw, a best practice identified in ERC-223, ERC-677, ERC-827 and OpenZeppelin’s implementation of SafeERC20.sol. ERC-20 defined an allowance feature, this caused a problem when called and then later modified to a different amount, as on OpenZeppelin issue #438. In ERC-721, there is no allowance because every NFT is unique, the quantity is none or one. Therefore we receive the benefits of ERC-20’s original design without problems that have been later discovered.
```

4. If the number of people who successfully called claim() = the number of winners, then owner can withdraw early. This means adding to the check in #1 the condition `|| numClaimed >= numWinners`

5. Make tests for cancel() and make sure the right people are refunded.

**Comment by EGreg** [comment]
Update: I did 1, 2

Do 3, 4, 5

**Comment by artman325** [comment]
> Do 3, 4, 5

Did 
[point3](https://github.com/Intercoin/AuctionContract/commit/8602902ba76ee07e907e45c938fcfc51a8b53a5f)
[point4](https://github.com/Intercoin/AuctionContract/commit/094b17c00beaf16039970129452c954bc2ba8e21)
[point5](https://github.com/Intercoin/AuctionContract/commit/cd6d2171228f72028e70c512f266f1278bee5697)
